/** Honest worker-shell help. Do not list container / js-exec / pnpm as available. */
export const OWNER_CLI_HELP = [
  'worker-shell · just-bash · not Linux',
  'builtins: cd  put|write  clear  help  examples  demo  vcode',
  'bins: ls cat pwd mkdir find tree curl jq file xan html-to-markdown echo grep sed awk',
  'voice: say ls · say demo · say write code greet.ts',
  'vcode writes under scratch/reports/artifacts only',
  'type demo — run official worker-shell PUT/GET/exec',
  'type examples — official catalog vs this shell',
  'not here: container/computerd · worker-javascript · pnpm · node · vim · git write',
].join('\n');

/** Why official examples/ do not appear as extra terminals. */
export const OWNER_CLI_EXAMPLES = [
  'this terminal = official examples/worker-shell',
  'same HTTP surface: PUT file · GET file · POST exec',
  'backend: just-bash via env.LOADER. no container.',
  'type demo — run that surface now',
  '',
  'not bound (upstream demos, not this CLI):',
  '  examples/container — computerd + Linux FUSE + capnweb',
  '  examples/worker-javascript — ESM eval, not a shell',
  '  examples/egress — none/all/custom policy playground',
  '  examples/mcp — Code Mode + Linux container MCP',
  '  examples/rlm — JS reducing long workspace context',
  '  examples/think — @cloudflare/think agent cwd',
  '  examples/think-compare-runtimes — side-by-side UI',
  '  examples/tutorial — pandoc/PDF on a Linux host',
  '  examples/artifacts — publish to CF Artifacts',
  '  examples/assets — Workers AI image + share link',
  '',
  'upstream packages (not extra terminals here):',
  '  packages/dofs · rpc · computerd · computer',
  '  packages/computer-computerd-linux-x64 (Docker image)',
  '',
  'partial here:',
  '  mcp — in-process computer + github (https). no Code Mode / no Linux',
  '  egress — curl uses direct. no none/all/custom playground',
  '',
  'binding the rest would be a second computer. this one stays worker-shell.',
].join('\n');
