-- =====================================================
-- SEED COMPLETO CAFÉ CURSOR FLORIANÓPOLIS
-- =====================================================

-- Limpiar datos existentes
DELETE FROM "EligibleUser";
DELETE FROM "Credit";

-- =====================================================
-- TODOS LOS CRÉDITOS REALES (59 disponibles)
-- =====================================================
INSERT INTO "Credit" ("id", "code", "link", "isUsed", "isTest", "createdAt", "updatedAt") VALUES 
('c1', 'IOCDK5XY8Y6V', 'https://cursor.com/referral?code=IOCDK5XY8Y6V', false, false, NOW(), NOW()),
('c2', 'QI2T7P4J6GHV', 'https://cursor.com/referral?code=QI2T7P4J6GHV', false, false, NOW(), NOW()),
('c3', 'IMCWTDS3ZXK', 'https://cursor.com/referral?code=IMCWTDS3ZXK', false, false, NOW(), NOW()),
('c4', 'ZQAVUFVJD76T', 'https://cursor.com/referral?code=ZQAVUFVJD76T', false, false, NOW(), NOW()),
('c5', '3OL6UOTHP17C', 'https://cursor.com/referral?code=3OL6UOTHP17C', false, false, NOW(), NOW()),
('c6', '4N23KPDMOVU', 'https://cursor.com/referral?code=4N23KPDMOVU', false, false, NOW(), NOW()),
('c7', '1X1I04SD9TH', 'https://cursor.com/referral?code=1X1I04SD9TH', false, false, NOW(), NOW()),
('c8', '6WHG9LUC9FLH', 'https://cursor.com/referral?code=6WHG9LUC9FLH', false, false, NOW(), NOW()),
('c9', 'TKIJESP22Q', 'https://cursor.com/referral?code=TKIJESP22Q', false, false, NOW(), NOW()),
('c10', 'M4472WWC7N4', 'https://cursor.com/referral?code=M4472WWC7N4', false, false, NOW(), NOW()),
('c11', 'X3KAZWGBB6PV', 'https://cursor.com/referral?code=X3KAZWGBB6PV', false, false, NOW(), NOW()),
('c12', 'IKOI7BMDKXRW', 'https://cursor.com/referral?code=IKOI7BMDKXRW', false, false, NOW(), NOW()),
('c13', '8XZOM9ULF8K', 'https://cursor.com/referral?code=8XZOM9ULF8K', false, false, NOW(), NOW()),
('c14', 'Y6JACXL4DJNB', 'https://cursor.com/referral?code=Y6JACXL4DJNB', false, false, NOW(), NOW()),
('c15', 'E4DPYCFIUYMA', 'https://cursor.com/referral?code=E4DPYCFIUYMA', false, false, NOW(), NOW()),
('c16', 'TQODTEQFCAB', 'https://cursor.com/referral?code=TQODTEQFCAB', false, false, NOW(), NOW()),
('c17', 'WJCW66LSRI', 'https://cursor.com/referral?code=WJCW66LSRI', false, false, NOW(), NOW()),
('c18', '5LBTDD8Q2B', 'https://cursor.com/referral?code=5LBTDD8Q2B', false, false, NOW(), NOW()),
('c19', 'YQB8EQS72RRF', 'https://cursor.com/referral?code=YQB8EQS72RRF', false, false, NOW(), NOW()),
('c20', 'QTFC6ZRZVFGG', 'https://cursor.com/referral?code=QTFC6ZRZVFGG', false, false, NOW(), NOW()),
('c21', 'U5CNF27LIR3X', 'https://cursor.com/referral?code=U5CNF27LIR3X', false, false, NOW(), NOW()),
('c22', 'DWNLZ8EBDMYA', 'https://cursor.com/referral?code=DWNLZ8EBDMYA', false, false, NOW(), NOW()),
('c23', 'X6NT1NQLDBBI', 'https://cursor.com/referral?code=X6NT1NQLDBBI', false, false, NOW(), NOW()),
('c24', 'LUJ4CAYLLTIR', 'https://cursor.com/referral?code=LUJ4CAYLLTIR', false, false, NOW(), NOW()),
('c25', 'XY3JNGPRZOHA', 'https://cursor.com/referral?code=XY3JNGPRZOHA', false, false, NOW(), NOW()),
('c26', 'Q3AV09VR4BME', 'https://cursor.com/referral?code=Q3AV09VR4BME', false, false, NOW(), NOW()),
('c27', 'JM0PW2PRXVIA', 'https://cursor.com/referral?code=JM0PW2PRXVIA', false, false, NOW(), NOW()),
('c28', 'CK0GBNFX166S', 'https://cursor.com/referral?code=CK0GBNFX166S', false, false, NOW(), NOW()),
('c29', 'IU8BB9EBPTAR', 'https://cursor.com/referral?code=IU8BB9EBPTAR', false, false, NOW(), NOW()),
('c30', '24CMVFAUWIXG', 'https://cursor.com/referral?code=24CMVFAUWIXG', false, false, NOW(), NOW()),
('c31', '5JIIR0ADXE', 'https://cursor.com/referral?code=5JIIR0ADXE', false, false, NOW(), NOW()),
('c32', 'HKROGNBBQMSD', 'https://cursor.com/referral?code=HKROGNBBQMSD', false, false, NOW(), NOW()),
('c33', 'YSTIOVGQY2E9', 'https://cursor.com/referral?code=YSTIOVGQY2E9', false, false, NOW(), NOW()),
('c34', 'GACD5QRKJYTY', 'https://cursor.com/referral?code=GACD5QRKJYTY', false, false, NOW(), NOW()),
('c35', 'EURHU2XOEI', 'https://cursor.com/referral?code=EURHU2XOEI', false, false, NOW(), NOW()),
('c36', 'QBYUYWCHFSG', 'https://cursor.com/referral?code=QBYUYWCHFSG', false, false, NOW(), NOW()),
('c37', 'XXTPV51359C', 'https://cursor.com/referral?code=XXTPV51359C', false, false, NOW(), NOW()),
('c38', 'KFYXZPJPYABT', 'https://cursor.com/referral?code=KFYXZPJPYABT', false, false, NOW(), NOW()),
('c39', '55AN98HKSIKV', 'https://cursor.com/referral?code=55AN98HKSIKV', false, false, NOW(), NOW()),
('c40', 'JSQBVSSBR4KY', 'https://cursor.com/referral?code=JSQBVSSBR4KY', false, false, NOW(), NOW()),
('c41', 'T6YF3MGB8SL', 'https://cursor.com/referral?code=T6YF3MGB8SL', false, false, NOW(), NOW()),
('c42', 'MXMVJPVOF8CO', 'https://cursor.com/referral?code=MXMVJPVOF8CO', false, false, NOW(), NOW()),
('c43', 'IPIY6MBUB6CX', 'https://cursor.com/referral?code=IPIY6MBUB6CX', false, false, NOW(), NOW()),
('c44', '9IJR8SXWTAOU', 'https://cursor.com/referral?code=9IJR8SXWTAOU', false, false, NOW(), NOW()),
('c45', 'GZBGRSYITWHI', 'https://cursor.com/referral?code=GZBGRSYITWHI', false, false, NOW(), NOW()),
('c46', 'NTOAWVLPOQU', 'https://cursor.com/referral?code=NTOAWVLPOQU', false, false, NOW(), NOW()),
('c47', 'KFAQSV8HVC0G', 'https://cursor.com/referral?code=KFAQSV8HVC0G', false, false, NOW(), NOW()),
('c48', 'XR1XTAG7TA02', 'https://cursor.com/referral?code=XR1XTAG7TA02', false, false, NOW(), NOW()),
('c49', 'IZULIVRSX89', 'https://cursor.com/referral?code=IZULIVRSX89', false, false, NOW(), NOW()),
('c50', 'WXGBYRC1PAAS', 'https://cursor.com/referral?code=WXGBYRC1PAAS', false, false, NOW(), NOW()),
('c51', 'HHIWD8DRG7F3', 'https://cursor.com/referral?code=HHIWD8DRG7F3', false, false, NOW(), NOW()),
('c52', 'VDEX5NFAHNHU', 'https://cursor.com/referral?code=VDEX5NFAHNHU', false, false, NOW(), NOW()),
('c53', 'VQYJB7KOMFWB', 'https://cursor.com/referral?code=VQYJB7KOMFWB', false, false, NOW(), NOW()),
('c54', 'QCZB7QMKCMW', 'https://cursor.com/referral?code=QCZB7QMKCMW', false, false, NOW(), NOW()),
('c55', 'M0KZ1WX0RX68', 'https://cursor.com/referral?code=M0KZ1WX0RX68', false, false, NOW(), NOW()),
('c56', 'KOYWMB71O6P2', 'https://cursor.com/referral?code=KOYWMB71O6P2', false, false, NOW(), NOW()),
('c57', 'SL5MZOO5BB88', 'https://cursor.com/referral?code=SL5MZOO5BB88', false, false, NOW(), NOW()),
('c58', 'XCSSEVEFJP4', 'https://cursor.com/referral?code=XCSSEVEFJP4', false, false, NOW(), NOW()),
('c59', 'D08IB7RAUS0Q', 'https://cursor.com/referral?code=D08IB7RAUS0Q', false, false, NOW(), NOW());

-- =====================================================
-- CRÉDITOS DE TEST (5)
-- =====================================================
INSERT INTO "Credit" ("id", "code", "link", "isUsed", "isTest", "createdAt", "updatedAt") VALUES 
('t1', 'TEST-CREDIT-001', 'https://cursor.com/referral?code=TEST-CREDIT-001', false, true, NOW(), NOW()),
('t2', 'TEST-CREDIT-002', 'https://cursor.com/referral?code=TEST-CREDIT-002', false, true, NOW(), NOW()),
('t3', 'TEST-CREDIT-003', 'https://cursor.com/referral?code=TEST-CREDIT-003', false, true, NOW(), NOW()),
('t4', 'TEST-CREDIT-004', 'https://cursor.com/referral?code=TEST-CREDIT-004', false, true, NOW(), NOW()),
('t5', 'TEST-CREDIT-005', 'https://cursor.com/referral?code=TEST-CREDIT-005', false, true, NOW(), NOW());

-- =====================================================
-- TODOS LOS USUARIOS ELEGIBLES (113 del evento + 5 test)
-- =====================================================
INSERT INTO "EligibleUser" ("id", "email", "name", "company", "role", "approvalStatus", "hasClaimed", "createdAt") VALUES 
('u1', 'andersonbosa0@gmail.com', 'Anderson Bosa', 'Mercado Livre', 'Desenvolvedor Backend', 'approved', false, NOW()),
('u2', 'alex+event@blockful.io', 'Alex Netto', 'blockful', 'founder', 'approved', false, NOW()),
('u3', 'rafael.benito@ifc.edu.br', 'Rafael Carlos Velez Benito', 'Instituto Federal Catarinense', 'Professor', 'approved', false, NOW()),
('u4', 'kevinrvb16@gmail.com', 'Kevin', 'Mercado Livre', 'Software Developer', 'approved', false, NOW()),
('u5', 'douglas.wnascimento@mercadolivre.com', 'Douglas Nascimento', 'Mercado Livre', 'Software Engineer', 'approved', false, NOW()),
('u6', 'ismaelheinzelmann@gmail.com', 'Ismael Coral Hoepers Heinzelmann', 'Mercado Livre', 'Software Developer', 'approved', false, NOW()),
('u7', 'jefferson@bleu.studio', 'Jefferson Bastos', 'Bleu', 'Software eng', 'approved', false, NOW()),
('u8', 'bibiana@bleu.studio', 'Bibiana Silva Correa', 'bleu builders', 'product designer', 'approved', false, NOW()),
('u9', 'jose@bleu.studio', 'Jose Ribeiro', 'bleu.builders', 'CEO', 'approved', false, NOW()),
('u10', 'rafaelmotta021@gmail.com', 'Rafael Michels Motta', 'Footprint', 'Head of Engineering', 'approved', false, NOW()),
('u11', 'gzmoreira5@gmail.com', 'Gabriel Zucco Moreira', 'Zero OS', 'Founder', 'approved', false, NOW()),
('u12', 'berohlfs@gmail.com', 'Bernardo Cruz Rohlfs', 'Sierra Studio', 'Software Engineer', 'approved', false, NOW()),
('u13', 'troy.g.erstling@gmail.com', 'Troy E', 'Susan David', 'Head of Sales', 'approved', false, NOW()),
('u14', 'wali@atom6studio.com', 'Walisson Feijo de Queiroz', 'Atomsix Studio', 'Head of Design', 'approved', false, NOW()),
('u15', 'aac.campos@gmail.com', 'Alexandre Campos', 'Udesc', 'Professor', 'approved', false, NOW()),
('u16', 'rodrigostuani@outlook.com', 'Rodrigo Stuani', 'Sesc SC', 'Analista de Sistemas', 'approved', false, NOW()),
('u17', 'pedro@sierra.studio', 'Pedro Kretzschmar', 'Sierra Studio', 'Head of Engineer', 'approved', false, NOW()),
('u18', 'joao@vipwebsul.com.br', 'Joao Vitor Santos', 'SIGA Software', 'Dev pleno', 'approved', false, NOW()),
('u19', 'carolineignacior@gmail.com', 'Ana Caroline Ignacio da Rosa', 'Superfiliate', 'Software Engineer', 'approved', false, NOW()),
('u20', 'evandro@superfiliate.com', 'Evandro Sasse', 'Superfiliate', 'CTO', 'approved', false, NOW()),
('u21', 'victor@superfiliate.com', 'Victor Feijo', 'Superfiliate', 'Head of Engineering', 'approved', false, NOW()),
('u22', 'ferrari.work@gmail.com', 'Helal Ferrari Cabral', 'Autonomo', 'Software Developer Java', 'approved', false, NOW()),
('u23', 'lucasrrc.pd@gmail.com', 'lucas rodrigues correia', 'atomsix', 'product designer', 'approved', false, NOW()),
('u24', 'pedrogoiozo@gmail.com', 'Pedro Kaua Goiozo Vieira', 'Viver de IA', 'Head of Growth', 'approved', false, NOW()),
('u25', 'felipe.g.datascience@gmail.com', 'Felipe Gabriel', 'Self employed', 'Data Scientist', 'approved', false, NOW()),
('u26', 'bruno.reisc@hotmail.com', 'Bruno', 'Dell Technologies', 'Technical Product Manager', 'approved', false, NOW()),
('u27', 'fraanckabral@gmail.com', 'Francine Cabral', 'blockful', 'Ops analyst', 'approved', false, NOW()),
('u28', 'danilosetubal@gmail.com', 'Danilo Setubal', 'Sesc-SC', 'Desenvolvedor de Software', 'approved', false, NOW()),
('u29', 'joaovictorsiga@gmail.com', 'Joao Victor dos Santos', 'SIGA Software', 'Dev Pleno', 'approved', false, NOW()),
('u30', 'nolanrsherman@gmail.com', 'Nolan', 'Buscando', 'Engenheiro de Software Senior', 'approved', false, NOW()),
('u31', 'gabrielbotelhomalenowitch@gmail.com', 'Gabriel Botelho Malenowitch', 'Stone Co.', 'Engenheiro de Software 3', 'approved', false, NOW()),
('u32', 'gustavopma90@gmail.com', 'Gustavo Prates Mendes de Aguiar', 'Prolog', 'Desenvolvedor front end', 'approved', false, NOW()),
('u33', 'ricrdev@gmail.com', 'Ricardo', 'Asksuite', 'Desenvolvedor', 'approved', false, NOW()),
('u34', 'jaisonn@gmail.com', 'Jaison Niehues', 'goodysac', 'cto', 'approved', false, NOW()),
('u35', 'burbes@gmail.com', 'NAELSON M JUNIOR', 'Globant', 'Senior Software Engineer', 'approved', false, NOW()),
('u36', 'daniel@unilevel.com.br', 'Daniel Godois', 'Unilevel Clinical', 'Ceo', 'approved', false, NOW()),
('u37', 'maxsonferovante@gmail.com', 'Maxson Almeida Ferovante', 'Compass OUL', 'Backend Software Engineer', 'approved', false, NOW()),
('u38', 'chrystian.profissional@gmail.com', 'Chrystian Ferreira da Silva', 'Sparkwise', 'Product Engineer', 'approved', false, NOW()),
('u39', 'ricardo@unovo.com.br', 'Ricardo Salles', 'Unovo', 'CTO', 'approved', false, NOW()),
('u40', 'vini@dynamic.xyz', 'Vinicius Macelai', 'Dynamic/Fireblocks', 'Senior Software Engineer', 'approved', false, NOW()),
('u41', 'bruno@shippit.app', 'Bruno Amorim', 'Shippit', 'Software Developer', 'approved', false, NOW()),
('u42', 'felipe.angeli@gmail.com', 'Felipe Angeli', 'Cappta', 'Dev senior', 'approved', false, NOW()),
('u43', 'joaogabriellima.eng@gmail.com', 'Joao', 'Tailwind Business Ventures', 'Head of AI', 'approved', false, NOW()),
('u44', 'adroaldof@gmail.com', 'Adroaldo De Andrade', 'InLabs Tech', 'Desenvolvedor', 'approved', false, NOW()),
('u45', 'luigiremor@gmail.com', 'Luigi Remor', 'Phase Labs', 'Founding Engineer', 'approved', false, NOW()),
('u46', 'rodrigo@geekzilla.com.br', 'Rodrigo da Costa', 'GeekZilla', 'Editor', 'approved', false, NOW()),
('u47', 'vitor.henckel@o2obots.com', 'Vitor Henckel', 'O2OBOTS', 'CTO', 'approved', false, NOW()),
('u48', 'feliperodriguesbroering@gmail.com', 'Felipe R Broering', 'Viaflex', 'CTO', 'approved', false, NOW()),
('u49', 'michelpm1@gmail.com', 'Michel Machado', 'Crescent', 'Tech Lead', 'approved', false, NOW()),
('u50', 'c.rm@live.com', 'Claudio R Mendonca', 'Compass', 'Engenheiro de dados', 'approved', false, NOW()),
('u51', 'maickel.carneiro@o2obots.com', 'Maickel Carneiro', 'O2OBots', 'Desenvolvedor', 'approved', false, NOW()),
('u52', 'bruno@ubiminds.com', 'Bruno Bruggemann', 'Ubiminds', 'Diretor', 'approved', false, NOW()),
('u53', 'rafaelescrich@gmail.com', 'Rafael Escrich', 'DFB Network', 'CTO', 'approved', false, NOW()),
('u54', 'enzonsb@gmail.com', 'Enzo Nicolas Spotorno Bieger', 'LISHA', 'AI Researcher and Tech Lead', 'approved', false, NOW()),
('u55', 'hudsoncoutinhoti@gmail.com', 'Hudson Coutinho', 'Linker bank', 'Head of Tecnology', 'approved', false, NOW()),
('u56', 'samuelssan28@gmail.com', 'Samuel Santos Araujo', 'Sizebay', 'Desenvolvedor de software', 'approved', false, NOW()),
('u57', 'elizziane@gmail.com', 'Elizziane Farias', 'Incodata', 'Arquiteta de Solucoes', 'approved', false, NOW()),
('u58', 'jgssimao@gmail.com', 'Jorge Gustavo Sandoval Simao', 'Aquarela Analytics', 'Engenheiro de Machine Learning', 'approved', false, NOW()),
('u59', 'nava.mateus@gmail.com', 'Mateus Nava', 'Reforge', 'Software engineer', 'approved', false, NOW()),
('u60', 'ritaalamino@gmail.com', 'Rita Carolina Alamino Borges Da Costa', 'SolTech Digital', 'CTO and Co-founder', 'approved', false, NOW()),
('u61', 'magirsca@gmail.com', 'Matheus', 'Deus', 'CEO/CTO/CDAIO', 'approved', false, NOW()),
('u62', 'valov.mikhail.a@gmail.com', 'MIKHAIL VALOV', 'Developer', 'Developer', 'approved', false, NOW()),
('u63', 'lalotrage@gmail.com', 'Lalo Trage', 'EscolaCripto', 'Founder', 'approved', false, NOW()),
('u64', 'steinert999@outlook.com', 'Guilherme Steinert de Azevedo', 'C6Bank', 'Senior Software Engineer', 'approved', false, NOW()),
('u65', 'info@astrologicmedia.com', 'Allan Woellner', 'Astrologic Games', 'Game Developer', 'approved', false, NOW()),
('u66', '4419970@gmail.com', 'Jose Carlos Menezes Junior', 'Reacher', 'Senior Software Engineer', 'approved', false, NOW()),
('u67', 'claytonrmendonca@gmail.com', 'Clayton Mendonca', 'ThoughtWorks', 'Senior Developer', 'approved', false, NOW()),
('u68', 'leonardo2sc@gmail.com', 'LEONARDO DE SOUZA CHAVES', 'Edge on Demand', 'Software Engineer', 'approved', false, NOW()),
('u69', 'vitorlavarda.souza@gmail.com', 'Vitor Lavarda de Souza', 'Freight Hero', 'Founding Software Engineer', 'approved', false, NOW()),
('u70', 'vitorlostada@hotmail.com', 'Vitor Lostada', 'Resleeve', 'Senior front-end developer', 'approved', false, NOW()),
('u71', 'jhoffmannburatto@gmail.com', 'Julia H Buratto', 'Jubs Studio', 'Founder', 'approved', false, NOW()),
('u72', 'lfniederauer@gmail.com', 'Luis Filipe Niederauer', 'Myself', 'Engenheiro', 'approved', false, NOW()),
('u73', 'silvioletras@gmail.com', 'Silvio Somer', 'RD Saude', 'Desenvolvedor PHP Senior', 'approved', false, NOW()),
('u74', 'matheusmski1@gmail.com', 'MATHEUS DOS SANTOS', 'Watch Brasil', 'Desenvolvedor senior', 'approved', false, NOW()),
('u75', 'vinicius.macelai@gmail.com', 'Vinicius Macelai', 'Fireblocks/Dynamic', 'Senior Software Engineer', 'approved', false, NOW()),
('u76', 'emanuelmarq@gmail.com', 'Toni Emanuel Marques', 'Casa', 'Head de Inovacao e TI', 'approved', false, NOW()),
('u77', 'faustino.alex@outlook.com', 'ALEX FAUSTINO COSTA', 'KopperERP', 'Desenvolvedor Frontend', 'approved', false, NOW()),
('u78', 'dani010646@gmail.com', 'Dani', 'Digito Service', 'Software Developer', 'approved', false, NOW()),
('u79', 'ejmatoso@gmail.com', 'Edison Matoso', 'Flash Tecnologia', 'Staff Engineer', 'approved', false, NOW()),
('u80', 'lucasperes.lpc@gmail.com', 'lucas peres coelho', 'LuizaLabs', 'Desenvolvedor Back-end', 'approved', false, NOW()),
('u81', 'brunotheodoro123@gmail.com', 'Bruno Theodoro', 'Picpay', 'Desenvolvedor back-end', 'approved', false, NOW()),
('u82', 'mathias.f.hemmer@gmail.com', 'Mathias Hemmer', 'Ambev', 'Desenvolvedor de Software', 'approved', false, NOW()),
('u83', 'bbrunomlla@gmail.com', 'Bruno Aguiar', 'Tea - Safe dating for women', 'Engenheiro de Software', 'approved', false, NOW()),
('u84', 'andreadam29@gmail.com', 'Andre Silva', 'BairesDev, TextNow', 'Software engineer', 'approved', false, NOW()),
('u85', 'eamaro@gmail.com', 'Eduardo Amaro Da Silva', 'DXC Technology', 'Account Manager', 'approved', false, NOW()),
('u86', 'iansaft.dev@gmail.com', 'Ian Saft', 'Agape Brasil', 'Desenvolvedor de Software', 'approved', false, NOW()),
('u87', 'dadornes@anysphere.co', 'Daniel Adornes', 'Anysphere / Cursor', 'Technical Support Engineer', 'approved', false, NOW()),
('u88', 'marketing@founderhaus.club', 'Founder Haus', 'Founder Haus', 'Community manager', 'approved', false, NOW()),
('u89', 'nitroxgas@gmail.com', 'George Alexandre Silva', 'Founder Haus', 'Phygital Team Member', 'approved', false, NOW()),
('u90', 'dalker@iroh.com.br', 'Dalker Walter', 'Iroh', 'Founder', 'approved', false, NOW()),
('u91', 'joaobornhausen@gmail.com', 'Joao Bornhausen', 'Hub primavera', 'socio', 'approved', false, NOW()),
('u92', 'luma.ramos93@gmail.com', 'Luma Ramos', 'Data Rudder', 'Analista de dados', 'approved', false, NOW()),
('u93', 'coolb01@proton.me', 'Miguelao C', 'Freelancer', 'Freelancer developer', 'approved', false, NOW()),
('u94', 'marcelo.mbarella22@gmail.com', 'Marcelo Barella', 'SigaSoft', 'Desenvolvedor', 'approved', false, NOW()),
('u95', 'gabenascimento1@gmail.com', 'Gabriel Nascimento', 'orda', 'Founding Engineer', 'approved', false, NOW()),
('u96', 'iamunhoz@gmail.com', 'Iva Apolonio Munhoz', 'Lailla.io', 'Desenvolvedor full stack', 'approved', false, NOW()),
('u97', 'torres.lucas@outlook.com', 'Lucas Torres', 'Vammo', 'Senior Engineer', 'approved', false, NOW()),
('u98', 'celio.gonzaga@arctouch.com', 'Celio Oliveira Gonzaga Junior', 'ArcTouch', 'Engenheiro de software', 'approved', false, NOW()),
('u99', 'maiasalvador@gmail.com', 'Mariana Maia Salvador de Assis', 'Mkplace', 'PM', 'approved', false, NOW()),
('u100', 'pedro@thedrops.com.br', 'Pedro Clivati', 'the drops', 'cofounder', 'approved', false, NOW()),
('u101', 'jeferson.marroni@gmail.com', 'Jefferson Marroni', 'Mullinkosson solucoes', 'Analista de QA', 'approved', false, NOW()),
('u102', 'felipe.valentin75@gmail.com', 'Felipe Valentin', 'Jusbrasil', 'Software engineer', 'approved', false, NOW()),
('u103', 'renan.inacio@coinbase.com', 'Renan Inacio', 'Coinbase', 'Senior Software Engineer - Frontend', 'approved', false, NOW()),
('u104', 'duylecampos@gmail.com', 'Duyle Campos', 'Tangelo.ai', 'Software Engineer', 'approved', false, NOW()),
('u105', 'rodrigo.branas@gmail.com', 'Rodrigo Branas', 'Compozy', 'CTO', 'approved', false, NOW()),
('u106', 'allanmainardes@gmail.com', 'Allan Mainardes', 'Mesha Tecnologia', 'Desenvolvedor', 'approved', false, NOW()),
('u107', 'gui.silva@tutanota.com', 'Guilherme Silva', 'Jusbrasil', 'Software Engineer', 'approved', false, NOW()),
('u108', 'pedro10rcorrea@gmail.com', 'Pedro Rodrigues Correa Neto', NULL, NULL, 'approved', false, NOW()),
('u109', 'heloiseapereira@gmail.com', 'Heloise Adriano Pereira', NULL, NULL, 'approved', false, NOW()),
('u110', 'lucasorionsouzadasilva@gmail.com', 'Lucas Orion', NULL, NULL, 'approved', false, NOW()),
('u111', 'ferrari.alexandre@gmail.com', 'Alexandre Ferrari', NULL, NULL, 'approved', false, NOW()),
('u112', 'mockraw@gmail.com', 'Christian Rios', NULL, NULL, 'approved', false, NOW()),
('u113', 'lucas_rc15@live.com', 'Lucas Rodrigues Correia', 'Atomsix', 'Product Designer', 'approved', false, NOW());

-- =====================================================
-- USUARIOS DE TEST
-- =====================================================
INSERT INTO "EligibleUser" ("id", "email", "name", "company", "role", "approvalStatus", "hasClaimed", "createdAt") VALUES 
('ut1', 'test@gmail.com', 'Test User 1', 'Test Company', 'Tester', 'approved', false, NOW()),
('ut2', 'test2@gmail.com', 'Test User 2', 'Test Company', 'Tester', 'approved', false, NOW()),
('ut3', 'test3@gmail.com', 'Test User 3', 'Test Company', 'Tester', 'approved', false, NOW()),
('ut4', 'test4@gmail.com', 'Test User 4', 'Test Company', 'Tester', 'approved', false, NOW()),
('ut5', 'test5@gmail.com', 'Test User 5', 'Test Company', 'Tester', 'approved', false, NOW());

-- =====================================================
-- VERIFICAR TOTALES
-- =====================================================
SELECT 'CREDITOS TOTALES' as info, COUNT(*) as total FROM "Credit";
SELECT 'CREDITOS DISPONIBLES' as info, COUNT(*) as total FROM "Credit" WHERE "isUsed" = false AND "isTest" = false;
SELECT 'CREDITOS TEST' as info, COUNT(*) as total FROM "Credit" WHERE "isTest" = true;
SELECT 'USUARIOS ELEGIBLES' as info, COUNT(*) as total FROM "EligibleUser";
