#!/usr/bin/env tsx
/**
 * Dreaming / consolidate — offline memory maintenance (CPU only).
 *
 * Weekly: pnpm dreaming
 * Produces a review report under memories/archived/ for human merge.
 * Full LLM merge can be added later (ReMe / O-Mem hooks).
 */

import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = process.cwd();
const BRAIN = join(ROOT, 'aileena_second_brain');
const MEMORIES = join(BRAIN, 'memories');
const ARCHIVED = join(MEMORIES, 'archived');

function walkMd(dir: string, base: string, acc: { rel: string; bytes: number; lines: number }[]): void {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) walkMd(full, base, acc);
    else if (name.endsWith('.md') && !name.startsWith('consolidate-report-')) {
      const rel = relative(BRAIN, full);
      const text = readFileSync(full, 'utf8');
      acc.push({ rel, bytes: text.length, lines: text.split('\n').length });
    }
  }
}

function tokenize(s: string): string[] {
  return s.toLowerCase().split(/[^a-z0-9\u4e00-\u9fff]+/).filter((t) => t.length > 3);
}

function main() {
  const files: { rel: string; bytes: number; lines: number }[] = [];
  walkMd(MEMORIES, BRAIN, files);

  const wordFreq = new Map<string, number>();
  for (const f of files) {
    const text = readFileSync(join(BRAIN, f.rel), 'utf8');
    for (const w of tokenize(text)) wordFreq.set(w, (wordFreq.get(w) ?? 0) + 1);
  }

  const episodic = files.filter((f) => f.rel.includes('memories/episodic/'));
  const staleCandidates = episodic.filter((f) => f.bytes < 200);
  const topTerms = [...wordFreq.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 24)
    .map(([w, c]) => `- ${w} (${c})`);

  const date = new Date().toISOString().slice(0, 10);
  mkdirSync(ARCHIVED, { recursive: true });
  const outPath = join(ARCHIVED, `consolidate-report-${date}.md`);

  const report = `# Dreaming report — ${date}

Auto-generated by \`pnpm dreaming\`. Review and merge into \`semantic/\` or \`personal/\` by hand.

## Inventory

| File | Lines | Bytes |
|------|-------|-------|
${files.map((f) => `| ${f.rel} | ${f.lines} | ${f.bytes} |`).join('\n')}

## Episodic → semantic candidates

${staleCandidates.length ? staleCandidates.map((f) => `- ${f.rel} (short — merge or archive)`).join('\n') : '_No short episodic files._'}

## Hot terms (dedup hints)

${topTerms.join('\n')}

## Next steps

1. Merge duplicate facts across semantic files
2. Promote reviewed episodic notes → \`memories/semantic/\`
3. Write one new skill under \`memories/procedural/skills/\` if a pattern repeats 3×
4. Run \`pnpm build:memory-index\` then deploy
5. Optional: run ReMeLight or O-Mem locally for LLM-assisted merge

## Hardware note

Dreaming runs offline — no GPU KV cache. Smaller indexed corpus = cheaper retrieval prefills at runtime.
`;

  writeFileSync(outPath, report);
  console.log(`[dreaming] wrote ${outPath}`);
  console.log(`[dreaming] ${files.length} memory files, ${episodic.length} episodic`);
}

main();
