import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { SkillPatch } from '../types';
import { repoRoot } from './paths';

export function generatedSkillsPath(start = process.cwd()): string {
  return join(repoRoot(start), 'aileena-new/lib/evolution/activeSkills.generated.ts');
}

export function codegenActiveSkills(skills: SkillPatch[], dest?: string): string {
  const site = skills.filter((s) => s.kind === 'site-agent');
  const body = `/**
 * AUTO-GENERATED by pnpm evolve. Do not edit by hand.
 * Verifiers live in ops/evolution/bank/verifiers.json — never import them here.
 */

import type { SkillKind } from './types';

export type ActiveSkill = {
  id: string;
  version: number;
  kind: SkillKind;
  triggers: string[];
  mustInclude: string[];
  mustNot: string[];
  replyGuidance: string;
  rootCause: string;
};

export const ACTIVE_SKILLS: ActiveSkill[] = ${JSON.stringify(
    site.map((s) => ({
      id: s.id,
      version: s.version,
      kind: s.kind,
      triggers: s.triggers,
      mustInclude: s.mustInclude,
      mustNot: s.mustNot,
      replyGuidance: s.replyGuidance,
      rootCause: s.rootCause,
    })),
    null,
    2,
  )};
`;
  const file = dest ?? generatedSkillsPath();
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, body);
  return file;
}
