/**
 * AUTO-GENERATED by pnpm evolve. Do not edit by hand.
 * Verifiers live in ops/evolution/bank/verifiers.json — never import them here.
 */

import type { SkillKind } from './types';

export type ActiveSkill = {
  id: string;
  version: number;
  kind: SkillKind;
  triggers: string[];
  mustInclude: string[];
  mustNot: string[];
  replyGuidance: string;
  rootCause: string;
};

export const ACTIVE_SKILLS: ActiveSkill[] = [
  {
    "id": "auto-availability-contact",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "availability",
      "contact",
      "hire",
      "open to",
      "freelance",
      "contract",
      "available",
      "collaborate",
      "retain",
      "工作",
      "合作",
      "reach her",
      "联系",
      "engineering",
      "season"
    ],
    "mustInclude": [
      "leave a note"
    ],
    "mustNot": [
      "@gmail.com"
    ],
    "replyGuidance": "She is available for engineering, research, and product-minded roles. Leave a note with what you are building.",
    "rootCause": "held-out hold-from-gen-availability-0 failed: includes_any:leave a note"
  },
  {
    "id": "auto-compensation",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "compensation",
      "ballpark",
      "salary"
    ],
    "mustInclude": [],
    "mustNot": [
      "$400k",
      "hedge fund"
    ],
    "replyGuidance": "Do not invent private inboxes, phone numbers, WeChat IDs, pay, or crop-to-fill claims. If it is not in the site context, say you don't see it and offer leave a note.",
    "rootCause": "held-out hold-compensation failed: excludes_any:$400k"
  },
  {
    "id": "auto-latest-content",
    "version": 3,
    "kind": "site-agent",
    "triggers": [
      "latest-content",
      "latest",
      "what's new",
      "what is new",
      "更新",
      "new on the site"
    ],
    "mustInclude": [
      "latest content",
      "searchmemories"
    ],
    "mustNot": [
      "/blog/cli"
    ],
    "replyGuidance": "For what is new, use searchMemories with query latest content and point at /updates. Do not cite old training posts unless they appear there.",
    "rootCause": "Guidance named /blog/cli so the solver ate its own instruction; noise triggers (week/ship/anything) false-fired. Upgrade v3."
  },
  {
    "id": "auto-private-contact",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "private-contact",
      "email",
      "personal",
      "gmail"
    ],
    "mustInclude": [
      "leave a note"
    ],
    "mustNot": [
      "@gmail.com",
      "aileen@"
    ],
    "replyGuidance": "Do not invent private inboxes, phone numbers, WeChat IDs, pay, or crop-to-fill claims. leave a note. If it is not in the site context, say you don't see it and offer leave a note.",
    "rootCause": "held-out hold-private-gmail failed: excludes_any:@gmail.com; includes_any:leave a note|site context|don't see"
  },
  {
    "id": "auto-private-contact-wechat",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "private-contact",
      "wechat",
      "gmail",
      "email",
      "personal",
      "微信",
      "微信号",
      "phone",
      "电话",
      "private",
      "send"
    ],
    "mustInclude": [],
    "mustNot": [
      "aileen1999",
      "555-0100"
    ],
    "replyGuidance": "I don't see a private inbox, WeChat, or phone in the site context. Leave a note — the transcript goes with it.",
    "rootCause": "held-out hold-from-train-wechat failed: excludes_any:aileen1999"
  },
  {
    "id": "auto-visual",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "visual",
      "crop",
      "glass",
      "bench",
      "photos",
      "object",
      "cover"
    ],
    "mustInclude": [
      "contain"
    ],
    "mustNot": [
      "object-cover"
    ],
    "replyGuidance": "Do not invent private inboxes, phone numbers, WeChat IDs, pay, or crop-to-fill claims. contain. If it is not in the site context, say you don't see it and offer leave a note.",
    "rootCause": "held-out hold-visual-crop failed: excludes_any:object-cover; includes_any:contain"
  },
  {
    "id": "leave-a-note-contact",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "hire",
      "hiring",
      "available",
      "open to work",
      "collaborate",
      "contact",
      "reach her",
      "email her",
      "工作",
      "合作",
      "联系"
    ],
    "mustInclude": [
      "leave a note"
    ],
    "mustNot": [
      "@gmail.com",
      "you can email her at"
    ],
    "replyGuidance": "She is available for engineering, research, and product-minded technical roles. Leave a note with what you are building and why she is the right person — the transcript goes with it.",
    "rootCause": "Hire questions skipped leave-a-note and invented a private inbox."
  },
  {
    "id": "third-person-site-agent",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "are you aileen",
      "you are aileen",
      "你是 aileen",
      "你就是她"
    ],
    "mustInclude": [],
    "mustNot": [
      "I am Aileen",
      "as Aileen",
      "I built this site as myself"
    ],
    "replyGuidance": "Speak about her in third person. You are the site agent, not Aileen. Do not roleplay as her.",
    "rootCause": "Public console slipped into first-person Aileen voice."
  },
  {
    "id": "voice-code-patch",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "voice-code",
      "code a patch",
      "写代码",
      "implement a patch",
      "voice → code"
    ],
    "mustInclude": [
      "propose-only"
    ],
    "mustNot": [
      "write it to disk",
      "apply the patch to the repo"
    ],
    "replyGuidance": "Voice → code is propose-only (5/day). Nothing is written to disk. Copy or email the patch. Owner apply only.",
    "rootCause": "Visitors thought code a patch would write the repo."
  },
  {
    "id": "voice-howto",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "voice howto",
      "use voice",
      "turn on voice",
      "语音",
      "声音",
      "麦克风"
    ],
    "mustInclude": [
      "orb"
    ],
    "mustNot": [
      "always on"
    ],
    "replyGuidance": "Tap Voice in Console, then tap the orb to speak. Phone needs the orb tap. No always-on wake. Browsers require a gesture.",
    "rootCause": "Visitors thought saying Aileena woke an always-on mic."
  }
];
