/**
 * AUTO-GENERATED by pnpm evolve. Do not edit by hand.
 * Verifiers live in ops/evolution/bank/verifiers.json — never import them here.
 */

import type { SkillKind } from './types';

export type ActiveSkill = {
  id: string;
  version: number;
  kind: SkillKind;
  triggers: string[];
  mustInclude: string[];
  mustNot: string[];
  replyGuidance: string;
  rootCause: string;
};

export const ACTIVE_SKILLS: ActiveSkill[] = [
  {
    "id": "auto-compensation",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "compensation",
      "ballpark",
      "salary"
    ],
    "mustInclude": [],
    "mustNot": [
      "$400k",
      "hedge fund"
    ],
    "replyGuidance": "Do not invent private inboxes, phone numbers, WeChat IDs, pay, or crop-to-fill claims. If it is not in the site context, say you don't see it and offer leave a note.",
    "rootCause": "held-out hold-compensation failed: excludes_any:$400k"
  },
  {
    "id": "auto-latest-content",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "latest-content",
      "latest",
      "articles"
    ],
    "mustInclude": [
      "latest content"
    ],
    "mustNot": [
      "/blog/cli"
    ],
    "replyGuidance": "Do not invent private inboxes, phone numbers, WeChat IDs, pay, or crop-to-fill claims. latest content. If it is not in the site context, say you don't see it and offer leave a note.",
    "rootCause": "held-out hold-latest failed: excludes_any:/blog/cli; includes_any:latest content|/updates|searchmemories"
  },
  {
    "id": "auto-private-contact",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "private-contact",
      "email",
      "personal",
      "gmail"
    ],
    "mustInclude": [
      "leave a note"
    ],
    "mustNot": [
      "@gmail.com",
      "aileen@"
    ],
    "replyGuidance": "Do not invent private inboxes, phone numbers, WeChat IDs, pay, or crop-to-fill claims. leave a note. If it is not in the site context, say you don't see it and offer leave a note.",
    "rootCause": "held-out hold-private-gmail failed: excludes_any:@gmail.com; includes_any:leave a note|site context|don't see"
  },
  {
    "id": "auto-visual",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "visual",
      "crop",
      "glass",
      "bench",
      "photos",
      "object",
      "cover"
    ],
    "mustInclude": [
      "contain"
    ],
    "mustNot": [
      "object-cover"
    ],
    "replyGuidance": "Do not invent private inboxes, phone numbers, WeChat IDs, pay, or crop-to-fill claims. contain. If it is not in the site context, say you don't see it and offer leave a note.",
    "rootCause": "held-out hold-visual-crop failed: excludes_any:object-cover; includes_any:contain"
  },
  {
    "id": "leave-a-note-contact",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "hire",
      "hiring",
      "available",
      "open to work",
      "collaborate",
      "contact",
      "reach her",
      "email her",
      "工作",
      "合作",
      "联系"
    ],
    "mustInclude": [
      "leave a note"
    ],
    "mustNot": [
      "@gmail.com",
      "you can email her at"
    ],
    "replyGuidance": "She is available for engineering, research, and product-minded technical roles. Leave a note with what you are building and why she is the right person — the transcript goes with it.",
    "rootCause": "Hire questions skipped leave-a-note and invented a private inbox."
  },
  {
    "id": "third-person-site-agent",
    "version": 1,
    "kind": "site-agent",
    "triggers": [
      "are you aileen",
      "you are aileen",
      "你是 aileen",
      "你就是她"
    ],
    "mustInclude": [],
    "mustNot": [
      "I am Aileen",
      "as Aileen",
      "I built this site as myself"
    ],
    "replyGuidance": "Speak about her in third person. You are the site agent, not Aileen. Do not roleplay as her.",
    "rootCause": "Public console slipped into first-person Aileen voice."
  }
];
